import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:share_plus/share_plus.dart';
import 'package:intl/intl.dart';
import '../../providers.dart';
import '../../theme/app_colors.dart';
import '../../theme/app_text.dart';
import '../../db/database.dart';

/// Weekly Report screen — §7.7
/// Read-only summary: hours per project, biggest score mover, Critical list.
class WeeklyReportScreen extends ConsumerWidget {
  const WeeklyReportScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final projectsAsync = ref.watch(homeProjectsProvider);

    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        backgroundColor: AppColors.background,
        elevation: 0,
        scrolledUnderElevation: 0,
        title: Text('Weekly Report', style: AppText.title()),
        leading: IconButton(
          icon: const Icon(Icons.close_rounded, color: AppColors.textSecondary),
          onPressed: () => context.pop(),
        ),
        actions: [
          IconButton(
            icon: const Icon(Icons.share_rounded, color: AppColors.textSecondary),
            onPressed: () => SharePlus.instance.share(ShareParams(text: 'My Pulse Weekly Report — generated by AEVORAX Pulse')),
          ),
        ],
      ),
      body: projectsAsync.when(
        loading: () => const Center(child: CircularProgressIndicator(strokeWidth: 1.5, color: AppColors.gold)),
        error: (e, _) => Center(child: Text('Error: $e', style: AppText.body())),
        data: (projects) => _ReportBody(projects: projects),
      ),
    );
  }
}

class _ReportBody extends ConsumerWidget {
  const _ReportBody({required this.projects});
  final List<Project> projects;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final weekLabel = 'Week of ${DateFormat("MMM d").format(DateTime.now().subtract(const Duration(days: 7)))} – ${DateFormat("MMM d").format(DateTime.now())}';

    return ListView(
      padding: const EdgeInsets.all(20),
      children: [
        Text(weekLabel, style: AppText.label().copyWith(color: AppColors.textSecondary)),
        const SizedBox(height: 20),
        _ReportSection(
          icon: Icons.access_time_rounded,
          title: 'Time This Week',
          child: Column(
            children: projects.map((p) => _ProjectHoursRow(project: p)).toList(),
          ),
        ),
        const SizedBox(height: 20),
        _ReportSection(
          icon: Icons.warning_amber_rounded,
          title: 'Critical Zone',
          child: _CriticalList(projects: projects),
        ),
        const SizedBox(height: 20),
        _ReportSection(
          icon: Icons.account_tree_outlined,
          title: 'Graph This Week',
          child: Text('${projects.length} active projects', style: AppText.body()),
        ),
      ],
    );
  }
}

class _ReportSection extends StatelessWidget {
  const _ReportSection({required this.icon, required this.title, required this.child});
  final IconData icon;
  final String title;
  final Widget child;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: AppColors.surface1,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: AppColors.borderDefault),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Icon(icon, size: 16, color: AppColors.gold),
              const SizedBox(width: 8),
              Text(title, style: AppText.titleSmall()),
            ],
          ),
          const SizedBox(height: 12),
          child,
        ],
      ),
    );
  }
}

class _ProjectHoursRow extends ConsumerWidget {
  const _ProjectHoursRow({required this.project});
  final Project project;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final sessionsAsync = ref.watch(projectSessionsProvider(project.id));
    final totalSecs = sessionsAsync.valueOrNull?.where((s) {
      final weekAgo = DateTime.now().subtract(const Duration(days: 7));
      return s.startedAt.isAfter(weekAgo) && s.endedAt != null;
    }).fold(0, (sum, s) => sum + (s.durationSeconds ?? 0)) ?? 0;
    final hours = (totalSecs / 3600).toStringAsFixed(1);

    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 4),
      child: Row(
        children: [
          Expanded(child: Text(project.name, style: AppText.bodyWhite())),
          Text('${hours}h', style: AppText.monoSmall()),
        ],
      ),
    );
  }
}

class _CriticalList extends ConsumerWidget {
  const _CriticalList({required this.projects});
  final List<Project> projects;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final criticalProjects = projects.where((p) {
      final logs = ref.watch(decayLogsProvider(p.id)).valueOrNull;
      return logs?.isNotEmpty == true && logs!.last.zone == 'critical';
    }).toList();

    if (criticalProjects.isEmpty) {
      return Text('No critical projects this week', style: AppText.body().copyWith(color: AppColors.zoneActiveFg));
    }

    return Column(
      children: criticalProjects.map((p) => Padding(
        padding: const EdgeInsets.symmetric(vertical: 3),
        child: Row(
          children: [
            Container(
              width: 8,
              height: 8,
              decoration: const BoxDecoration(
                color: AppColors.zoneCriticalFg,
                borderRadius: BorderRadius.all(Radius.circular(2)),
              ),
            ),
            const SizedBox(width: 8),
            Text(p.name, style: AppText.bodyWhite().copyWith(color: AppColors.zoneCriticalFg)),
          ],
        ),
      )).toList(),
    );
  }
}
